### PR TITLE
Change getting started cta to look less like a warning

### PR DESCRIPTION
**Pull request by SeanHealy33**
Closes https://github.com/ember-learn/builds/issues/59

screenshot from 2018-04-29 19-35-28

### CODE REVIEW

**Comment by locks** [comment]
I am partial to completely removing it. Seems to fit our newest direction better.

**Comment by SeanHealy33** [comment]
Hey guys any update on where/how to add new CSS classes for this project?

I'm not sure I should mess with the minified file on [master](https://github.com/ember-learn/builds/blob/master/app/styles/app.css) to add the `border-left`.

**Comment by SeanHealy33** [comment]
Sounds good, I'll create a pr a little later to add a new style class on the website then 👍

**Comment by locks** [comment]
Thank you for your contribution @SeanHealy33!
The team recently decided that the warning is no longer as relevant as it was, and that it is better if the first thing people see is the header and the graphic, instead of a message that directs them elsewhere. I have added that change on top of yours to move this PR to completion :)

**Pull request merged**
